spring: 
  jpa: 
    hibernate: 
      ddl-auto: create
  datasource: 
    url: jdbc:mysql://localhost:3306/biblioteca?useTimezone=true&serverTimezone=UTC
    username: root
    password: vertrigo
    driverClassName: com.mysql.cj.jdbc.Driver